# Generated by Django 4.2 on 2023-04-09 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='rate',
            field=models.IntegerField(null=True),
        ),
    ]
