# Generated by Django 4.1.7 on 2023-04-10 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiapp', '0002_vehicle_rate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver',
            name='car_model',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='license_number',
        ),
        migrations.AddField(
            model_name='driver',
            name='address',
            field=models.CharField(default='nothing', max_length=30),
        ),
        migrations.AddField(
            model_name='driver',
            name='email',
            field=models.CharField(default='nothing', max_length=18),
        ),
        migrations.AddField(
            model_name='driver',
            name='image',
            field=models.ImageField(default='nothing', upload_to='drimg/'),
        ),
        migrations.AddField(
            model_name='driver',
            name='license',
            field=models.FileField(default='nothing', upload_to='license/'),
        ),
        migrations.AddField(
            model_name='driver',
            name='password',
            field=models.CharField(default='nothing', max_length=18),
        ),
        migrations.AddField(
            model_name='driver',
            name='phone',
            field=models.IntegerField(default='1'),
        ),
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.CharField(default='nothing', max_length=30),
        ),
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(default='nothing', upload_to='drimg/'),
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.IntegerField(default='1'),
        ),
    ]
