# Generated by Django 4.2 on 2023-04-11 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiapp', '0006_alter_driver_address_alter_user_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='email',
            field=models.CharField(default='nothing', max_length=50),
        ),
    ]
