# Generated by Django 4.1.7 on 2023-04-30 06:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vehiapp', '0009_alter_vehicle_userid'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vehiapp.vehicle'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='status',
            field=models.CharField(default='not booked', max_length=20),
        ),
    ]
