# Generated by Django 4.1.7 on 2023-04-30 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiapp', '0010_booking_vehicle_vehicle_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='fare',
            field=models.FloatField(blank=True),
        ),
    ]
