# Generated by Django 4.1.7 on 2023-05-04 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiapp', '0011_alter_booking_fare'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='fare',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
