# Generated by Django 4.1.7 on 2023-05-04 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiapp', '0013_booking_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='date',
            field=models.TimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='time',
            field=models.DateField(auto_now=True),
        ),
    ]
