# Generated by Django 4.2 on 2023-05-23 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiapp', '0015_auto_20230504_2128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='license',
            field=models.ImageField(default='nothing', upload_to='license/'),
        ),
    ]
