# Generated by Django 4.2 on 2023-05-23 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiapp', '0017_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='distance',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
