# Generated by Django 4.2 on 2023-05-23 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehiapp', '0018_booking_distance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='fare',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='rating',
        ),
    ]
